[package]
name = "cat"
version = "0.1.0"
authors = ["Yishu See <yishuyishu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exitfailure = "0.5.1"
failure = "0.1.5"
structopt = "0.2.10"
